language: go

go:
- 1.8

before_install:
- export PATH=/home/travis/gopath/bin:$PATH

install:
- mkdir -p $GOPATH/bin
- go get -u github.com/golang/dep/cmd/dep
- dep init
- dep ensure

script:
- go test