language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

before_install: :
  - go env
  - go mod download

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
