
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20160617.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.0.0-rc.1"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.3"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.9.1"
  source = "https://github.com/grpc/grpc-go.git"

[[override]]
  name = "google.golang.org/genproto"
  source = "https://github.com/google/go-genproto.git"

[[override]]
  name = "golang.org/x/net"
  source = "https://github.com/golang/net.git"

[[override]]
  name = "golang.org/x/text"
  source = "https://github.com/golang/text.git"